<a href="https://colab.research.google.com/github/fhalilov/school/blob/master/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
my_list = [1,2,3]

In [8]:
np.arange(0,100,2.1)

array([ 0. ,  2.1,  4.2,  6.3,  8.4, 10.5, 12.6, 14.7, 16.8, 18.9, 21. ,
       23.1, 25.2, 27.3, 29.4, 31.5, 33.6, 35.7, 37.8, 39.9, 42. , 44.1,
       46.2, 48.3, 50.4, 52.5, 54.6, 56.7, 58.8, 60.9, 63. , 65.1, 67.2,
       69.3, 71.4, 73.5, 75.6, 77.7, 79.8, 81.9, 84. , 86.1, 88.2, 90.3,
       92.4, 94.5, 96.6, 98.7])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(1,10,22)

array([ 1.        ,  1.42857143,  1.85714286,  2.28571429,  2.71428571,
        3.14285714,  3.57142857,  4.        ,  4.42857143,  4.85714286,
        5.28571429,  5.71428571,  6.14285714,  6.57142857,  7.        ,
        7.42857143,  7.85714286,  8.28571429,  8.71428571,  9.14285714,
        9.57142857, 10.        ])

In [17]:
np.random.randint(1,23,(4,3))

array([[ 8, 22,  7],
       [ 9, 13, 21],
       [14, 18, 17],
       [12, 19, 14]])

In [19]:
np.random.seed(101)

np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [0]:
np.random.seed(101)

arr= np.random.randint(0,100,10)

In [21]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [24]:
arr.max()

95

In [25]:
arr.min()

9

In [26]:
arr.mean()

60.8

In [28]:
arr.argmax()

0

In [29]:
arr.argmin()

7

In [31]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [0]:
mat = np.arange(0,100).reshape(10,10)

In [35]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
mat[1,2]

12

In [38]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
mat > 30

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])